name: baemin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: "^0.2.2"
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/

  fonts:
    - family: Noto_Sans_KR
      fonts:
        - asset: assets/font/Noto_Sans_KR/NotoSansKR-Thin.otf
          weight: 100
        - asset: assets/font/Noto_Sans_KR/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/font/Noto_Sans_KR/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/font/Noto_Sans_KR/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/font/Noto_Sans_KR/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/font/Noto_Sans_KR/NotoSansKR-Black.otf
          weight: 900
    - family: Nanum_Gothic
      fonts:
        - asset: assets/font/Nanum_Gothic/NanumGothic-Regular.ttf
          weight: 400
        - asset: assets/font/Nanum_Gothic/NanumGothic-ExtraBold.ttf
          weight: 700
        - asset: assets/font/Nanum_Gothic/NanumGothic-Bold.ttf
          weight: 800
    - family: BMHANNA_11yrs
      fonts:
        - asset: assets/font/BMHANNA_11yrs/BMHANNA_11yrs.ttf
    - family: BMHANNA_air
      fonts:
        - asset: assets/font/BMHANNA/BMHANNAAir.ttf
    - family: BMHANNA_pro
      fonts:
        - asset: assets/font/BMHANNA/BMHANNAPro.ttf
